version: '2'
services:
  api-gateway:
    #build: .
    image: kmendezp/api-gateway
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 4000 -b '0.0.0.0'"
    ports:
      - "4000:4000"
